# -*- coding: utf-8 -*-
"""Music Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10j8TWsuWut4skgsScrRQ7rWNVBg7jcgN
"""

import os
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np

# Path to your MFCC files
mfcc_folder_path = '/content/Songs'  # Replace with your actual folder path

# List to store the compressed data for each file
compressed_data = []

# Loop through each MFCC file
for file_name in sorted(os.listdir(mfcc_folder_path)):
    if file_name.endswith('.csv'):  # Assuming your files are in CSV format
        # Load the MFCC data
        file_path = os.path.join(mfcc_folder_path, file_name)
        data = pd.read_csv(file_path, header=None)  # Load without headers

        # Check if the data has 20 rows
        if data.shape[0] == 20:
            # Apply PCA to compress to 1 column
            pca = PCA(n_components=1)
            data_compressed = pca.fit_transform(data)  # updated
            # perpx = 5
            # tsne = TSNE(n_components=1, perplexity=perpx)
            # data_compressed = tsne.fit_transform(data)

            # data_compressed = data.mean(axis = 1)

            # data_compressed = data.std(axis = 1)

            # Store the compressed data as a DataFrame for further processing or saving
            compressed_df = pd.DataFrame(data_compressed)
            compressed_data.append(compressed_df)
        else:
            print(f"Warning: {file_name} does not have 20 rows, it has {data.shape[0]} rows.")

# # Combine all compressed data into one DataFrame if needed
# # This will give you a DataFrame with 20 rows and columns for each compressed file
# all_compressed_data = pd.concat(compressed_data, axis=1)

# # Display the resulting DataFrame shape
# print(all_compressed_data.shape)  # This will show (20, number_of_files)

# # Optionally, display or save the result
# print(all_compressed_data)

"""EDA Starts!"""

######## Heat Map #########
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the MFCC data from a CSV or TXT file
mfcc_data = pd.read_csv('/content/Songs/03-MFCC.csv', header=None)  # Replace with your actual file path

# Plot the heatmap
plt.figure(figsize=(12, 6))
sns.heatmap(mfcc_data, cmap='coolwarm', xticklabels=10, yticklabels=True)
plt.title('MFCC Heatmap')
plt.xlabel('Time Frames')
plt.ylabel('MFCC Coefficients')
plt.show()

print(mfcc_data.shape)
mfcc_data

######## Correlation matrix ########
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the MFCC data from a CSV file
mfcc_data_1 = pd.read_csv('/content/Songs/03-MFCC.csv', header=None)  # Replace with your actual file path
mfcc_data = mfcc_data_1.T.copy()

# Compute the correlation matrix between the MFCC coefficients
corr_matrix = mfcc_data.corr()

# Plot the correlation matrix as a heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=False, cmap='coolwarm', xticklabels=10, yticklabels=10)
plt.title('Correlation Matrix of MFCC Coefficients')
plt.xlabel('MFCC Coefficients')
plt.ylabel('MFCC Coefficients')
plt.show()

########### Histogram of coefficients ###########
import pandas as pd
import matplotlib.pyplot as plt

# Load the MFCC data from a CSV file (or TXT file)
mfcc_data = pd.read_csv('/content/Songs/03-MFCC.csv', header=None)  # Replace with your actual file path

# Get the number of MFCC coefficients (rows)
n_mfcc = mfcc_data.shape[0]  # Number of rows (MFCC coefficients)

# Plot histograms for each MFCC coefficient
plt.figure(figsize=(18, 100))

# Iterate through each MFCC coefficient (row)
for i in range(n_mfcc):
    plt.subplot(n_mfcc, 1, i+1)  # Create subplots for each coefficient
    plt.hist(mfcc_data.iloc[i, :], bins=30, color='skyblue', edgecolor='black')  # Histogram of each row
    plt.title(f'Histogram of MFCC Coefficient {i+1}')
    plt.xlabel('Value')
    plt.ylabel('Occurance')

plt.tight_layout()  # Adjust layout for better spacing
plt.show()

"""EDA Ends!!"""

# Combine all compressed data into one DataFrame if needed
# This will give you a DataFrame with 20 rows and columns for each compressed file
all_compressed_data = pd.concat(compressed_data, axis=1)

# Display the resulting DataFrame shape
print(all_compressed_data.shape)  # This will show (20, number_of_files)

# Optionally, display or save the result
all_compressed_data

new_data = all_compressed_data.T.copy(deep = True)
print(new_data.shape)
new_data

# # Standardizing dataframe
from sklearn.preprocessing import StandardScaler

# # Initialize the StandardScaler
scaler = StandardScaler()

# # Standardize the DataFrame (mean = 0, std = 1)
new_data_1 = pd.DataFrame(scaler.fit_transform(new_data), columns=new_data.columns)

# # Display the standardized DataFrame
new_data_1

perpx = 23
n_comps = 1
tsne = TSNE(n_components=n_comps, perplexity=perpx)
# pca= PCA(n_components=n_comps)
new_data_2 = pd.DataFrame(tsne.fit_transform(new_data_1))
new_data_2

# # Standardizing dataframe
from sklearn.preprocessing import StandardScaler

# # Initialize the StandardScaler
scaler = StandardScaler()

# # Standardize the DataFrame (mean = 0, std = 1)
new_data_3 = pd.DataFrame(scaler.fit_transform(new_data_2), columns=new_data_2.columns)

# # Display the standardized DataFrame
new_data_3

# from sklearn.cluster import KMeans
# from sklearn.mixture import GaussianMixture
# import numpy as np

# # If you haven't loaded your data yet, you can replace this with actual data loading code
# # For example: data = pd.read_csv('your_data.csv').values

# # Set the number of clusters
# num_clusters = 6  # Choose a reasonable number based on your data; adjust as needed

# # Initialize and fit the KMeans model
# kmeans = KMeans(n_clusters=num_clusters, random_state=42)
# kmeans.fit(new_data)
# # gm = GaussianMixture(n_components=num_clusters, random_state=42)
# # gm.fit(new_data)

# # Get the cluster assignments for each data point
# cluster_labels = kmeans.labels_
# #cluster_labels = gm.predict(new_data)

# # Optional: Get the cluster centers
# # cluster_centers = kmeans.cluster_centers_

# # Display results
# # print("Cluster labels for each sample:", cluster_labels)
# # print("Coordinates of cluster centers:\n", cluster_centers)
# # len(cluster_labels)

############## Heirarchial Clustering ##################
import numpy as np
import pandas as pd
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
import seaborn as sns


clustering = AgglomerativeClustering(n_clusters=6, metric='euclidean', linkage='ward')
labels = clustering.fit_predict(new_data_3)


# Optional: Add the labels to your dataframe (if you are using a dataframe)
# df['Cluster'] = labels

# from sklearn.metrics import silhouette_score
#hard_labels = gm.predict(new_data)
# sil_score = silhouette_score(new_data, cluster_labels)
# print("Silhouette Score:", sil_score)

# bic_score = gm.bic(new_data)
# print(f"BIC Score: {bic_score}")

from sklearn.metrics import silhouette_score
score = silhouette_score(new_data_3, labels)
print("Silhouette Score:", score)

from sklearn.metrics import davies_bouldin_score
score = davies_bouldin_score(new_data_3, labels)
print("Davies-Bouldin Index:", score)